// Reserved words for referral codes (case-insensitive)
export const reservedReferralCodes = [
  // Brand and platform
  "WEETOO",
  "WEETOOAPP",
  "WEETOONET",
  "WEETOOADMIN",
  "WEETOOSUPPORT",
  // Admin/moderation
  "ADMIN",
  "MOD",
  "MODERATOR",
  "STAFF",
  "SUPPORT",
  "HELP",
  "ROOT",
  "OWNER",
  "SYSTEM",
  "SYSADMIN",
  "SUPERUSER",
  "SUPERADMIN",
  "SUPER-ADMIN",
  "SUP3RADMIN",
  "SUP3R-ADMIN",
  // Generic/official
  "OFFICIAL",
  "TEAM",
  "CONTACT",
  "INFO",
  "SERVICE",
  "CUSTOMER",
  "USER",
  "USERNAME",
  "ACCOUNT",
  "TEST",
  "DEMO",
  // Payment/finance
  "PAYMENT",
  "BANK",
  "CARD",
  "CREDIT",
  "DEPOSIT",
  "WITHDRAW",
  "MONEY",
  "CASH",
  "COIN",
  "KORCOIN",
  "KORCOINS",
  "BITCOIN",
  "BTC",
  "ETH",
  "CRYPTO",
  "NFT",
  // Common social/impersonation
  "FACEBOOK",
  "TWITTER",
  "X",
  "INSTAGRAM",
  "INSTA",
  "SNAPCHAT",
  "TIKTOK",
  "YOUTUBE",
  "GOOGLE",
  "APPLE",
  "MICROSOFT",
  "AMAZON",
  "SUPPORT",
  "ADMINISTRATOR",
  // Variations and leetspeak
  "ADM1N",
  "SUPP0RT",
  "0FFICIAL",
  "0WNER",
  "5UPPORT",
  "5TAFF",
  "CUST0MER",
  "5YSTEM",
  "5YSADMIN",
  "5UPERUSER",
  "T3AM",
  "C0IN",
  "K0RCOIN",
  "K0RCOINS",
  // Short/obvious
  "ROOT",
  "GOD",
  "NULL",
  "VOID",
  "ALL",
  "NONE",
  "DEFAULT",
  "UNKNOWN",
  "ANONYMOUS",
  "ANON",
  "GUEST",
  "ADMIN1",
  "ADMIN2",
  "ADMIN3",
  // Numbers only
  "1234",
  "0000",
  "1111",
  "2222",
  "3333",
  "4444",
  "5555",
  "6666",
  "7777",
  "8888",
  "9999",
];

// Reserved patterns for referral codes (case-insensitive)
export const reservedReferralPatterns = [
  /admin$/i, // ends with admin
  /^admin/i, // starts with admin
  /^admin[0-9a-z]+$/i, // admin followed by numbers/letters (e.g., ADMIN12, ADMINXYZ)
  /super\s*-?\s*admin/i, // superadmin, super-admin, super admin
  /^support/i, // starts with support
  /mod(erator)?/i, // contains mod or moderator
  /staff/i,
  /owner/i,
  /sys(admin)?/i, // sys or sysadmin
  /team/i,
  /official/i,
  /service/i,
  /customer/i,
  /root/i,
  /superuser/i,
  /test/i,
  /demo/i,
  /user(name)?/i,
  /account/i,
  /contact/i,
  /help/i,
  /anonymous/i,
  /anon/i,
  /guest/i,
  /nft/i,
  /korcoin(s)?/i,
  /bitcoin/i,
  /btc/i,
  /eth/i,
  /crypto/i,
  /bank/i,
  /card/i,
  /payment/i,
  /deposit/i,
  /withdraw/i,
  /money/i,
  /cash/i,
  /facebook/i,
  /twitter/i,
  /instagram/i,
  /snapchat/i,
  /tiktok/i,
  /youtube/i,
  /google/i,
  /apple/i,
  /microsoft/i,
  /amazon/i,
];
